// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaQsdqAAq8ioIuZomGcN2Uq30wnhAGEEU',
    appId: '1:373868429207:web:4b157ceb9a5d7fbc194ed2',
    messagingSenderId: '373868429207',
    projectId: 'flutter-680cb',
    authDomain: 'flutter-680cb.firebaseapp.com',
    storageBucket: 'flutter-680cb.firebasestorage.app',
    measurementId: 'G-SWVJ0B91TC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDykaS4zZW87uYkerCfNL1CbRNNXQzjRpc',
    appId: '1:373868429207:android:8ed70d529735f598194ed2',
    messagingSenderId: '373868429207',
    projectId: 'flutter-680cb',
    storageBucket: 'flutter-680cb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDE6J5MtBceIrGRS6mtO28QfIMgzurF15k',
    appId: '1:373868429207:ios:c791d987d5fac964194ed2',
    messagingSenderId: '373868429207',
    projectId: 'flutter-680cb',
    storageBucket: 'flutter-680cb.firebasestorage.app',
    iosBundleId: 'com.example.firebaseapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDE6J5MtBceIrGRS6mtO28QfIMgzurF15k',
    appId: '1:373868429207:ios:c791d987d5fac964194ed2',
    messagingSenderId: '373868429207',
    projectId: 'flutter-680cb',
    storageBucket: 'flutter-680cb.firebasestorage.app',
    iosBundleId: 'com.example.firebaseapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAaQsdqAAq8ioIuZomGcN2Uq30wnhAGEEU',
    appId: '1:373868429207:web:20ccbf32ae9439d5194ed2',
    messagingSenderId: '373868429207',
    projectId: 'flutter-680cb',
    authDomain: 'flutter-680cb.firebaseapp.com',
    storageBucket: 'flutter-680cb.firebasestorage.app',
    measurementId: 'G-H4G04G17SM',
  );
}
